language: ruby
rvm:
  - 2.3.0
services:
  - redis-server
before_install: gem install bundler -v 1.11.2
addons:
  code_climate:
    repo_token: cb8d449140f18d812206507cd0aa79a6e82a76af0f03671372171fcb19dd987d
